#!/bin/sh
cd /boot/home/projects/Rondel/PackagingFolder
package create -b rondel_0.8.4.3-1_gcc2.hpkg
sleep 0.5
package add rondel_0.8.4.3-1_gcc2.hpkg data apps bin documentation
sleep 0.5
addattr BeShare:Info "Markdown-capable Text Editor" rondel_0.8.4.3-1_gcc2.hpkg
becopy rondel_0.8.4.3-1_gcc2.hpkg "/Storage/Haiku/My ports"
mv rondel_0.8.4.3-1_gcc2.hpkg /boot/home/projects/repo2

